import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import {Resend} from 'resend';

// https://vite.dev/config/
export default defineConfig(({ mode }) => {
  // Load environment variables so we can access RESEND_API_KEY
  const env = loadEnv(mode, process.cwd(), '');
  const resend = new Resend(env.RESEND_API_KEY);

  return {
    plugins: [
      react(),
      // Custom plugin to handle emails on the same port
      {
        name: 'email-backend',
        configureServer(server) {
          server.middlewares.use('/api/sendEmail', (req, res, next) => {
            if (req.method === 'POST') {
              let body = '';
              
              req.on('data', chunk => {
                body += chunk.toString();
              });

              req.on('end', async () => {
                try {
                  const { email, locationName, aiContent } = JSON.parse(body);
                  
                  // Convert plain text newlines into HTML breaks
                  const formattedContent = aiContent.replace(/\n/g, '<br/>');

                  // Custom HTML Template matching her UI theme
                  const htmlTemplate = `
                    <!DOCTYPE html>
                    <html>
                      <head>
                        <style>
                          @import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@600;700&family=Inter:wght@300;400;500&display=swap');
                          body { font-family: 'Inter', sans-serif; background-color: #042346; padding: 40px 20px; margin: 0; }
                          .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 25px; padding: 40px; box-shadow: 0 15px 40px rgba(0,0,0,0.4); }
                          h1 { font-family: 'Cormorant Garamond', serif; color: #164c7a; font-size: 35px; margin-top: 0; border-bottom: 2px solid #e8f2ff; padding-bottom: 15px; }
                          p { color: #444444; line-height: 1.8; font-size: 16px; }
                          .footer { margin-top: 35px; text-align: center; color: #888888; font-size: 13px; }
                        </style>
                      </head>
                      <body>
                        <div class="container">
                          <h1>✨ Travel Guide: ${locationName}</h1>
                          <p>${formattedContent}</p>
                          <div class="footer">Generated by AI & Sent from your Travel App</div>
                        </div>
                      </body>
                    </html>
                  `;

                  // Send via Resend
                  const data = await resend.emails.send({
                    from: 'Travel App <onboarding@resend.dev>', // Change if a custom domain is verified later
                    to: 'ved.patilll21@gmail.com',
                    subject: `Your AI Travel Guide for ${locationName}`,
                    html: htmlTemplate,
                  });

                  res.setHeader('Content-Type', 'application/json');
                  res.end(JSON.stringify({ success: true, data }));
                } catch (error) {
                  res.statusCode = 500;
                  res.setHeader('Content-Type', 'application/json');
                  res.end(JSON.stringify({ success: false, error: error.message }));
                }
              });
            } else {
              // Pass all other requests (like normal frontend loading) to Vite
              next();
            }
          });
        }
      }
    ],
  }
})